export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './branchController.service';
import { BranchControllerService } from './branchController.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './exchangeRateController.service';
import { ExchangeRateControllerService } from './exchangeRateController.service';
export * from './roleController.service';
import { RoleControllerService } from './roleController.service';
export * from './testController.service';
import { TestControllerService } from './testController.service';
export * from './transactionController.service';
import { TransactionControllerService } from './transactionController.service';
export * from './transactionItemController.service';
import { TransactionItemControllerService } from './transactionItemController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthControllerService, BranchControllerService, CustomerControllerService, ExchangeRateControllerService, RoleControllerService, TestControllerService, TransactionControllerService, TransactionItemControllerService, UserControllerService];
