/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address { 
    id?: string;
    email: string;
    phone?: string;
    street?: string;
    woreda?: string;
    kebele?: string;
    subCity?: string;
    postalCode?: string;
    createdAt?: string;
    updatedAt?: string;
}

