/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transaction } from './transaction';
import { Customer } from './customer';


export interface BankAccount { 
    id?: string;
    accountNumber?: string;
    createdAt?: string;
    updatedAt?: string;
    customer?: Customer;
    transactions?: Set<Transaction>;
}

