/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Address } from './address';


export interface Branch { 
    id?: string;
    branchCode?: string;
    name?: string;
    createDate?: string;
    updateDate?: string;
    address?: Address;
    users?: Set<User>;
}

