/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankAccountDto } from './bankAccountDto';
import { Address } from './address';
import { Transaction } from './transaction';
import { UserPublicDto } from './userPublicDto';


export interface CustomerDto { 
    id?: string;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    address?: Address;
    dateOfBirth?: string;
    identificationType?: CustomerDto.IdentificationTypeEnum;
    identificationNumber?: string;
    createDate?: string;
    updateDate?: string;
    user?: UserPublicDto;
    bankAccounts?: Set<BankAccountDto>;
    transactions?: Set<Transaction>;
}
export namespace CustomerDto {
    export type IdentificationTypeEnum = 'PASSPORT' | 'NATIONAL_IDENTIFICATION' | 'DRIVER_LICENSE';
    export const IdentificationTypeEnum = {
        Passport: 'PASSPORT' as IdentificationTypeEnum,
        NationalIdentification: 'NATIONAL_IDENTIFICATION' as IdentificationTypeEnum,
        DriverLicense: 'DRIVER_LICENSE' as IdentificationTypeEnum
    };
}


