/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Currency } from './currency';


export interface ExchangeRate { 
    id?: string;
    baseCurrency?: Currency;
    targetCurrency?: Currency;
    rate?: number;
    transactionType?: string;
    createDate?: string;
    updateDate?: string;
}

