/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Currency } from './currency';


export interface ExchangeRateDto { 
    id?: string;
    baseCurrency?: Currency;
    targetCurrency?: Currency;
    rate?: number;
    transactionType?: ExchangeRateDto.TransactionTypeEnum;
    createDate?: string;
    updateDate?: string;
}
export namespace ExchangeRateDto {
    export type TransactionTypeEnum = 'PURCHASE' | 'SELL';
    export const TransactionTypeEnum = {
        Purchase: 'PURCHASE' as TransactionTypeEnum,
        Sell: 'SELL' as TransactionTypeEnum
    };
}


