/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionItemDto } from './transactionItemDto';


export interface PaginatedResponseDTOTransactionItemDto { 
    content?: Array<TransactionItemDto>;
    currentPage?: number;
    pageSize?: number;
    total?: number;
}

