/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionDto } from './transactionDto';


export interface PaginatedResponseDTOTransactionDto { 
    content?: Array<TransactionDto>;
    currentPage?: number;
    pageSize?: number;
    total?: number;
}

