/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerDto } from './customerDto';


export interface PaginatedResponseDTOCustomerDto { 
    content?: Array<CustomerDto>;
    currentPage?: number;
    pageSize?: number;
    total?: number;
}

