/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExchangeRateDto } from './exchangeRateDto';


export interface PaginatedResponseDTOExchangeRateDto { 
    content?: Array<ExchangeRateDto>;
    currentPage?: number;
    pageSize?: number;
    total?: number;
}

