/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPublicDto } from './userPublicDto';


export interface PaginatedResponseDTOUserPublicDto { 
    content?: Array<UserPublicDto>;
    currentPage?: number;
    pageSize?: number;
    total?: number;
}

