/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionDto { 
    id?: string;
    module?: PermissionDto.ModuleEnum;
    access?: PermissionDto.AccessEnum;
}
export namespace PermissionDto {
    export type ModuleEnum = 'USER_MANAGEMENT' | 'TRANSACTION_MANAGEMENT' | 'REPORT_MANAGEMENT' | 'EXCHANGE_RATES_MANAGEMENT';
    export const ModuleEnum = {
        UserManagement: 'USER_MANAGEMENT' as ModuleEnum,
        TransactionManagement: 'TRANSACTION_MANAGEMENT' as ModuleEnum,
        ReportManagement: 'REPORT_MANAGEMENT' as ModuleEnum,
        ExchangeRatesManagement: 'EXCHANGE_RATES_MANAGEMENT' as ModuleEnum
    };
    export type AccessEnum = 'READ' | 'WRITE';
    export const AccessEnum = {
        Read: 'READ' as AccessEnum,
        Write: 'WRITE' as AccessEnum
    };
}


