/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';


export interface Role { 
    id?: string;
    name?: Role.NameEnum;
    permissions?: Set<Permission>;
}
export namespace Role {
    export type NameEnum = 'ROLE_ADMIN' | 'ROLE_USER' | 'ROLE_MODERATOR';
    export const NameEnum = {
        Admin: 'ROLE_ADMIN' as NameEnum,
        User: 'ROLE_USER' as NameEnum,
        Moderator: 'ROLE_MODERATOR' as NameEnum
    };
}


