/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionDto } from './permissionDto';


export interface RoleDto { 
    roleId?: string;
    name?: RoleDto.NameEnum;
    permissions?: Set<PermissionDto>;
}
export namespace RoleDto {
    export type NameEnum = 'ROLE_ADMIN' | 'ROLE_USER' | 'ROLE_MODERATOR';
    export const NameEnum = {
        Admin: 'ROLE_ADMIN' as NameEnum,
        User: 'ROLE_USER' as NameEnum,
        Moderator: 'ROLE_MODERATOR' as NameEnum
    };
}


