/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExchangeRate } from './exchangeRate';
import { Transaction } from './transaction';


export interface TransactionItemDto { 
    id?: string;
    exchangeRate?: ExchangeRate;
    amount?: number;
    createDate?: string;
    updateDate?: string;
    transaction?: Transaction;
}

