/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { TransactionItem } from './transactionItem';
import { Customer } from './customer';
import { BankAccount } from './bankAccount';
import { TravelDocument } from './travelDocument';


export interface Transaction { 
    ticketNumber?: number;
    permitNumber?: string;
    transactionType?: Transaction.TransactionTypeEnum;
    transactionStatus?: Transaction.TransactionStatusEnum;
    totalAmount?: number;
    createDate?: string;
    updateDate?: string;
    user?: User;
    customer?: Customer;
    paymentMethodType?: Transaction.PaymentMethodTypeEnum;
    bankAccount?: BankAccount;
    transactionItems?: Set<TransactionItem>;
    travelDocument?: TravelDocument;
}
export namespace Transaction {
    export type TransactionTypeEnum = 'PURCHASE' | 'SELL';
    export const TransactionTypeEnum = {
        Purchase: 'PURCHASE' as TransactionTypeEnum,
        Sell: 'SELL' as TransactionTypeEnum
    };
    export type TransactionStatusEnum = 'PENDING' | 'APPROVED' | 'CANCELLED' | 'COMPLETED';
    export const TransactionStatusEnum = {
        Pending: 'PENDING' as TransactionStatusEnum,
        Approved: 'APPROVED' as TransactionStatusEnum,
        Cancelled: 'CANCELLED' as TransactionStatusEnum,
        Completed: 'COMPLETED' as TransactionStatusEnum
    };
    export type PaymentMethodTypeEnum = 'CASH' | 'BANK_TRANSFER' | 'CARD';
    export const PaymentMethodTypeEnum = {
        Cash: 'CASH' as PaymentMethodTypeEnum,
        BankTransfer: 'BANK_TRANSFER' as PaymentMethodTypeEnum,
        Card: 'CARD' as PaymentMethodTypeEnum
    };
}


