/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transaction } from './transaction';


export interface TravelDocument { 
    id?: string;
    passportNumber?: string;
    nationality?: string;
    airTicket?: string;
    residenceId?: string;
    countryOfResidence?: string;
    residenceExpires?: string;
    visaNumber?: string;
    visaType?: string;
    visaIssuedBy?: string;
    visaIssuedOn?: string;
    visaValidity?: string;
    purposeOfTravel?: string;
    createDate?: string;
    updateDate?: string;
    transaction?: Transaction;
}

