/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Address } from './address';
import { Customer } from './customer';
import { Branch } from './branch';


export interface User { 
    id?: string;
    username?: string;
    email: string;
    password: string;
    firstName?: string;
    lastName?: string;
    status?: User.StatusEnum;
    address?: Address;
    branch?: Branch;
    customers?: Set<Customer>;
    roles?: Set<Role>;
    createDate?: string;
    updateDate?: string;
}
export namespace User {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE' | 'DELETED';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum,
        Deleted: 'DELETED' as StatusEnum
    };
}


